### ISSUE TITLE
Update LNEL chart ES-2 embedded in Excel with additional legend scale information

### ISSUE THREAD

**Issue by jufemaiz** [ARKInvest/SolarBatteryBitcoin#1]
Resources tab embeds the chart labelled:

> Figure ES-2. Frequency of negative real-time power prices in 2017

This is poorly representing the data that was used to generate the chart. You'll find that in the [resource](https://escholarship.org/content/qt1qd5b2d9/qt1qd5b2d9.pdf) in Figure 13 on page 31. This is actually a subset of the power prices, as per 4.1.2:

> **4.1.2 Increases in the frequency of negative prices**
>
> The percentage of nodes with negative RT prices during 5% or more of all hours grew rapidly between 2015 and 2017, though some years in the 2009–2012 period also had a substantial percentage of nodes with frequent occurrences of negative prices (Figure 12). As discussed below, the frequent negative prices in the 2009–2012 period were driven in part by limited transmission in the wind-rich region of West Texas prior to the CREZ transmission expansion as well as high hydropower levels in the West. The prevalence of nodes with negative DA prices during 5% or more of all hours followed a similar pattern, albeit with much smaller percentages of such nodes.

Alternatively amending the legend to be one twentieth of the number presented would be required (or alternatively, give the number of hours explicitly).

**Comment by brettwinton** [comment]
Deleted this graphic. Was something that I had pulled from a document and wanted to talk through with the team, but is unrelated to the model and not used (and causes confusion out of context).
